# Generated by Django 5.2.15 on 2026-06-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fuelstation',
            new_name='routes_fuel_state_34c75b_idx',
            old_name='routes_fuel_state_2d9f8f_idx',
        ),
        migrations.RenameIndex(
            model_name='fuelstation',
            new_name='routes_fuel_price_p_d680b8_idx',
            old_name='routes_fuel_price_37e680_idx',
        ),
    ]
